require('dotenv').config();
const express=require('express'),cors=require('cors'),multer=require('multer'),path=require('path'),fs=require('fs'),crypto=require('crypto'),jwt=require('jsonwebtoken');
const { S3Client, PutObjectCommand, GetObjectCommand } = require('@aws-sdk/client-s3');
const pool=require('./db/pool'); const app=express(); const PORT=process.env.PORT||4004; const PUBLIC_BASE_URL=process.env.PUBLIC_BASE_URL||`http://localhost:${PORT}`;
const uploadDir=path.join(__dirname,'..','uploads'); fs.mkdirSync(uploadDir,{recursive:true});
const storage=multer.diskStorage({destination:uploadDir,filename:(_r,file,cb)=>{const ext=path.extname(file.originalname).toLowerCase()||'.jpg';cb(null,`${Date.now()}-${crypto.randomUUID()}${ext}`)}});
const upload=multer({storage,limits:{fileSize:5*1024*1024},fileFilter:(_r,file,cb)=>cb(null,/^image\/(jpeg|png|webp|gif)$/i.test(file.mimetype))});
const s3=process.env.S3_BUCKET ? new S3Client({region:process.env.AWS_REGION||'us-east-1'}) : null;
const objectUrl=(key)=>`${PUBLIC_BASE_URL}/api/uploads/object/${encodeURIComponent(key)}`;
const allowedOrigins = String(process.env.CORS_ORIGINS || '*').split(',').map(v => v.trim()).filter(Boolean);
const corsOptions = { origin(origin, cb) { if (!origin || allowedOrigins.includes('*') || allowedOrigins.includes(origin)) return cb(null, true); return cb(new Error('Origin not allowed by CORS')); } };

app.use(cors(corsOptions));app.use(express.json());app.use('/api/uploads/object',express.static(uploadDir));
app.get('/api/uploads/object/:key',async(req,res,next)=>{if(!s3)return next();try{const out=await s3.send(new GetObjectCommand({Bucket:process.env.S3_BUCKET,Key:req.params.key}));res.setHeader('Content-Type',out.ContentType||'application/octet-stream');out.Body.pipe(res)}catch(e){res.status(e.name==='NoSuchKey'?404:500).json({error:'Unable to load image'})}});
app.get('/health',(_r,s)=>s.json({status:'ok',service:'catalog-service'}));
function adminOnly(req,res,next){const token=(req.headers.authorization||'').replace(/^Bearer\s+/i,'');if(!token)return res.status(401).json({error:'Authorization token required'});try{const p=jwt.verify(token,process.env.JWT_SECRET||'change-this-secret-in-production');if(p.role!=='ADMIN')return res.status(403).json({error:'Admin access required'});req.user=p;next()}catch{return res.status(401).json({error:'Invalid or expired token'})}}
app.post('/api/uploads',adminOnly,upload.single('image'),async(req,res)=>{if(!req.file)return res.status(400).json({error:'Image file is required'});try{if(s3){const key=`catalog-${Date.now()}-${crypto.randomUUID()}${path.extname(req.file.originalname).toLowerCase()||'.jpg'}`;await s3.send(new PutObjectCommand({Bucket:process.env.S3_BUCKET,Key:key,Body:fs.createReadStream(req.file.path),ContentType:req.file.mimetype}));fs.unlinkSync(req.file.path);return res.status(201).json({url:objectUrl(key)});}return res.status(201).json({url:`${PUBLIC_BASE_URL}/api/uploads/object/${req.file.filename}`});}catch(e){console.error(e);if(req.file?.path&&fs.existsSync(req.file.path))fs.unlinkSync(req.file.path);res.status(500).json({error:'Unable to upload image'})}});
app.get('/api/restaurants',async(_q,res)=>{try{res.json((await pool.query('SELECT * FROM restaurants ORDER BY created_at DESC')).rows)}catch(e){console.error(e);res.status(500).json({error:'Unable to load restaurants'})}});
app.get('/api/restaurants/:id',async(req,res)=>{try{const r=await pool.query('SELECT * FROM restaurants WHERE id=$1',[req.params.id]);if(!r.rowCount)return res.status(404).json({error:'Restaurant not found'});res.json(r.rows[0])}catch(e){res.status(500).json({error:'Unable to load restaurant'})}});
app.post('/api/restaurants',adminOnly,async(req,res)=>{const{name,cuisine,address,imageUrl,rating=4.2,deliveryMinutes=35,isOpen=true}=req.body;if(!name||!cuisine)return res.status(400).json({error:'name and cuisine are required'});try{const r=await pool.query('INSERT INTO restaurants(id,name,cuisine,address,image_url,rating,delivery_minutes,is_open) VALUES($1,$2,$3,$4,$5,$6,$7,$8) RETURNING *',[crypto.randomUUID(),name,cuisine,address||'',imageUrl||null,rating,deliveryMinutes,isOpen]);res.status(201).json(r.rows[0])}catch(e){console.error(e);res.status(500).json({error:'Unable to create restaurant'})}});
app.patch('/api/restaurants/:id',adminOnly,async(req,res)=>{const{name,cuisine,address,imageUrl,rating,deliveryMinutes,isOpen}=req.body;try{const r=await pool.query('UPDATE restaurants SET name=COALESCE($1,name),cuisine=COALESCE($2,cuisine),address=COALESCE($3,address),image_url=COALESCE($4,image_url),rating=COALESCE($5,rating),delivery_minutes=COALESCE($6,delivery_minutes),is_open=COALESCE($7,is_open),updated_at=now() WHERE id=$8 RETURNING *',[name,cuisine,address,imageUrl,rating,deliveryMinutes,isOpen,req.params.id]);if(!r.rowCount)return res.status(404).json({error:'Restaurant not found'});res.json(r.rows[0])}catch(e){console.error(e);res.status(500).json({error:'Unable to update restaurant'})}});
app.delete('/api/restaurants/:id',adminOnly,async(req,res)=>{try{const r=await pool.query('DELETE FROM restaurants WHERE id=$1 RETURNING id',[req.params.id]);if(!r.rowCount)return res.status(404).json({error:'Restaurant not found'});res.json({success:true})}catch(e){res.status(500).json({error:'Unable to delete restaurant'})}});
app.get('/api/menu',async(req,res)=>{try{const q=req.query.restaurantId;const r=await pool.query(`SELECT m.*,r.name AS restaurant_name FROM menu_items m JOIN restaurants r ON r.id=m.restaurant_id ${q?'WHERE m.restaurant_id=$1':''} ORDER BY m.created_at DESC`,q?[q]:[]);res.json(r.rows)}catch(e){console.error(e);res.status(500).json({error:'Unable to load menu'})}});
app.post('/api/menu',adminOnly,async(req,res)=>{const{restaurantId,name,description='',category='Main Course',price,imageUrl,isVeg=false,isEnabled=true}=req.body;if(!restaurantId||!name||price===undefined)return res.status(400).json({error:'restaurantId, name and price are required'});try{const r=await pool.query('INSERT INTO menu_items(id,restaurant_id,name,description,category,price,image_url,is_veg,is_enabled) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9) RETURNING *',[crypto.randomUUID(),restaurantId,name,description,category,price,imageUrl||null,isVeg,isEnabled]);res.status(201).json(r.rows[0])}catch(e){console.error(e);res.status(500).json({error:'Unable to create food'})}});
app.patch('/api/menu/:id',adminOnly,async(req,res)=>{const{restaurantId,name,description,category,price,imageUrl,isVeg,isEnabled}=req.body;try{const r=await pool.query('UPDATE menu_items SET restaurant_id=COALESCE($1,restaurant_id),name=COALESCE($2,name),description=COALESCE($3,description),category=COALESCE($4,category),price=COALESCE($5,price),image_url=COALESCE($6,image_url),is_veg=COALESCE($7,is_veg),is_enabled=COALESCE($8,is_enabled),updated_at=now() WHERE id=$9 RETURNING *',[restaurantId,name,description,category,price,imageUrl,isVeg,isEnabled,req.params.id]);if(!r.rowCount)return res.status(404).json({error:'Food not found'});res.json(r.rows[0])}catch(e){console.error(e);res.status(500).json({error:'Unable to update food'})}});
app.delete('/api/menu/:id',adminOnly,async(req,res)=>{try{const r=await pool.query('DELETE FROM menu_items WHERE id=$1 RETURNING id',[req.params.id]);if(!r.rowCount)return res.status(404).json({error:'Food not found'});res.json({success:true})}catch(e){res.status(500).json({error:'Unable to delete food'})}});
const initSql=fs.readFileSync(path.join(__dirname,'db','init.sql'),'utf8');
pool.query(initSql).then(()=>app.listen(PORT,()=>console.log(`Catalog service listening on port ${PORT}`))).catch((e)=>{console.error('Catalog DB init failed',e);process.exit(1)});
