import { logout, useAppAuth } from './auth.js';
import AuthPage from './AuthPage.jsx';
import React,{useEffect,useState} from 'react';
import {BrowserRouter,Link,Route,Routes} from 'react-router-dom';
import axios from 'axios';
import './index.css';
const ORDER_SERVICE_URL=import.meta.env.VITE_ORDER_SERVICE_URL||'http://localhost:4000';
const CATALOG_URL=import.meta.env.VITE_CATALOG_SERVICE_URL||'http://localhost:4004';
const RESTAURANT_ID=import.meta.env.VITE_RESTAURANT_ID||'11111111-1111-1111-1111-111111111111';
const fallback='https://images.unsplash.com/photo-1547592180-85f173990554?auto=format&fit=crop&w=700&q=80';
const NEXT_STATUS={PLACED:'ACCEPTED',ACCEPTED:'PREPARING',PREPARING:'OUT_FOR_DELIVERY'};
function Nav(){return <div className="app-nav"><Link className="nav-brand" to="/">🍳 LoyalEats Restaurant</Link><div className="nav-links"><Link to="/">Dashboard</Link><Link to="/menu">Menu</Link><Link to="/orders">Orders</Link><button onClick={logout}>Logout</button></div></div>}
function Dashboard(){const [r,setR]=useState(null),[orders,setOrders]=useState([]);useEffect(()=>{axios.get(`${CATALOG_URL}/api/restaurants/${RESTAURANT_ID}`).then(x=>setR(x.data));const f=()=>axios.get(`${ORDER_SERVICE_URL}/api/orders`,{params:{restaurantId:RESTAURANT_ID}}).then(x=>setOrders(x.data));f();const t=setInterval(f,5000);return()=>clearInterval(t)},[]);return <><div className="brand-lockup"><div><span className="eyebrow">RESTAURANT CONSOLE</span><h1>{r?.name||'Restaurant dashboard'}</h1><p className="lead">Manage incoming orders and keep customers updated.</p></div>{r&&<span className="test-pill">{r.is_open?'● OPEN':'● CLOSED'}</span>}</div><div className="stats-grid"><div className="card stat"><span>Orders</span><strong>{orders.length}</strong></div><div className="card stat"><span>Rating</span><strong>★ {r?.rating||'—'}</strong></div><div className="card stat"><span>Delivery</span><strong>{r?.delivery_minutes||'—'} min</strong></div></div><div className="card"><h2>Recent orders</h2>{orders.slice(0,4).map(o=><OrderCard key={o.id} order={o} compact/>)}{!orders.length&&<p>No orders yet.</p>}</div></>}
function Menu(){const [items,setItems]=useState([]);useEffect(()=>{axios.get(`${CATALOG_URL}/api/menu`,{params:{restaurantId:RESTAURANT_ID}}).then(r=>setItems(r.data))},[]);return <><div className="section-title"><span className="eyebrow">MENU</span><h1>Your food catalog</h1></div><div className="food-grid">{items.map(i=><div className="food-card" key={i.id}><img src={i.image_url||fallback}/><div className="food-copy"><h3>{i.name}</h3><p>{i.description}</p><div className="food-bottom"><strong>${Number(i.price).toFixed(2)}</strong><span className={`status-dot ${i.is_enabled?'on':'off'}`}>{i.is_enabled?'Enabled':'Disabled'}</span></div></div></div>)}</div></>}
function OrderCard({order,compact=false}){const [busy,setBusy]=useState(false);const advance=async()=>{const next=NEXT_STATUS[order.status];if(!next)return;setBusy(true);try{await axios.patch(`${ORDER_SERVICE_URL}/api/orders/${order.id}/status`,{status:next});window.location.reload()}finally{setBusy(false)}};return <div className="order-card card"><div className="section-heading"><div><h3>Order #{order.id.slice(0,8).toUpperCase()}</h3><p>{new Date(order.created_at).toLocaleString()}</p></div><span className={`badge badge-${order.status.toLowerCase()}`}>{order.status}</span></div><div className="order-items">{(order.items||[]).map((i,idx)=><div className="order-item" key={idx}><img src={i.imageUrl||fallback}/><div><strong>{i.quantity} × {i.name}</strong><span>${(Number(i.price)*i.quantity).toFixed(2)}</span></div></div>)}</div><p><strong>Payment:</strong> {order.payment_status} · <strong>Total:</strong> ${Number(order.total_amount).toFixed(2)}</p><p><strong>Deliver to:</strong> {order.delivery_address}</p>{!compact&&<div className="action-row">{NEXT_STATUS[order.status]&&<button disabled={busy} onClick={advance}>Mark {NEXT_STATUS[order.status]}</button>}{!['DELIVERED','CANCELLED'].includes(order.status)&&<button className="danger-btn" onClick={()=>axios.patch(`${ORDER_SERVICE_URL}/api/orders/${order.id}/status`,{status:'CANCELLED'}).then(()=>window.location.reload())}>Cancel</button>}</div>}</div>}
function Orders(){const [orders,setOrders]=useState([]);useEffect(()=>{const f=()=>axios.get(`${ORDER_SERVICE_URL}/api/orders`,{params:{restaurantId:RESTAURANT_ID}}).then(r=>setOrders(r.data));f();const t=setInterval(f,5000);return()=>clearInterval(t)},[]);return <><div className="section-title"><span className="eyebrow">ORDERS</span><h1>Incoming food orders</h1></div>{orders.map(o=><OrderCard key={o.id} order={o}/>)}{!orders.length&&<div className="card"><p>No incoming orders.</p></div>}</>}
function App(){useAppAuth();return <BrowserRouter><Routes><Route path="/login" element={<AuthPage/>}/><Route path="/register" element={<AuthPage/>}/><Route path="*" element={<ProtectedRoutes/>}/></Routes></BrowserRouter>}
function ProtectedRoutes(){return <div className="container"><Nav/><Routes><Route path="/" element={<Dashboard/>}/><Route path="/menu" element={<Menu/>}/><Route path="/orders" element={<Orders/>}/><Route path="*" element={<Dashboard/>}/></Routes></div>}
export default App;
